# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'SRT-IOS-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SRT-IOS-App
  pod 'SRT-IOS-XCFramework', :path => '../'
end
